version: '3.8'

name: ws-chat

services:
  database:
    image: mongo
    container_name: chat-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
